CREATE TABLE IF NOT EXISTS iot_device_access_error_log (
    id BIGINT NOT NULL COMMENT '主键',
    tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
    trace_id VARCHAR(64) DEFAULT NULL COMMENT 'trace id',
    protocol_code VARCHAR(64) DEFAULT NULL COMMENT '协议编码',
    request_method VARCHAR(16) DEFAULT NULL COMMENT '请求方式',
    failure_stage VARCHAR(32) DEFAULT NULL COMMENT '失败阶段',
    device_code VARCHAR(64) DEFAULT NULL COMMENT '设备编码',
    product_key VARCHAR(64) DEFAULT NULL COMMENT '产品Key',
    gateway_device_code VARCHAR(64) DEFAULT NULL COMMENT '网关设备编码',
    sub_device_code VARCHAR(64) DEFAULT NULL COMMENT '子设备编码',
    topic_route_type VARCHAR(32) DEFAULT NULL COMMENT 'topic 路由类型',
    message_type VARCHAR(32) DEFAULT NULL COMMENT '消息类型',
    topic VARCHAR(255) DEFAULT NULL COMMENT 'topic',
    client_id VARCHAR(128) DEFAULT NULL COMMENT '客户端ID',
    payload_size INT DEFAULT NULL COMMENT 'payload 大小',
    payload_encoding VARCHAR(16) DEFAULT NULL COMMENT 'payload 编码',
    payload_truncated TINYINT NOT NULL DEFAULT 0 COMMENT 'payload 是否截断',
    raw_payload LONGTEXT DEFAULT NULL COMMENT '原始 payload',
    error_code VARCHAR(64) DEFAULT NULL COMMENT '错误码',
    exception_class VARCHAR(255) DEFAULT NULL COMMENT '异常类型',
    error_message VARCHAR(500) DEFAULT NULL COMMENT '错误消息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_access_error_trace (trace_id),
    KEY idx_access_error_device_time (device_code, create_time),
    KEY idx_access_error_stage_time (failure_stage, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备接入失败归档表';
