package com.ghlzm.iot.system.service.model;

public record GovernanceWorkItemCommand(
        String workItemCode,
        String subjectType,
        Long subjectId,
        Long productId,
        Long riskMetricId,
        Long releaseBatchId,
        Long approvalOrderId,
        String traceId,
        String deviceCode,
        String productKey,
        Long assigneeUserId,
        String sourceStage,
        String blockingReason,
        String snapshotJson,
        String taskCategory,
        String domainCode,
        String actionCode,
        String executionStatus,
        String recommendationSnapshotJson,
        String evidenceSnapshotJson,
        String impactSnapshotJson,
        String rollbackSnapshotJson,
        String priorityLevel,
        Long operatorUserId
) {
    public GovernanceWorkItemCommand(
            String workItemCode,
            String subjectType,
            Long subjectId,
            Long productId,
            Long riskMetricId,
            Long releaseBatchId,
            Long approvalOrderId,
            String traceId,
            String deviceCode,
            String productKey,
            Long assigneeUserId,
            String sourceStage,
            String blockingReason,
            String snapshotJson,
            String priorityLevel,
            Long operatorUserId
    ) {
        this(
                workItemCode,
                subjectType,
                subjectId,
                productId,
                riskMetricId,
                releaseBatchId,
                approvalOrderId,
                traceId,
                deviceCode,
                productKey,
                assigneeUserId,
                sourceStage,
                blockingReason,
                snapshotJson,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                priorityLevel,
                operatorUserId
        );
    }
}
