spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/spring_boot_iot_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 2
      timeout: 10s

logging:
  level:
    root: info
    com.ghlzm.iot: info

iot:
  mqtt:
    broker-url: tcp://127.0.0.1:1883
    username: admin
    password: public

  telemetry:
    storage-type: mysql

  rule:
    enabled: true
