spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: ${IOT_MYSQL_URL:jdbc:mysql://8.130.107.120:3306/rm_iot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false}
          username: ${IOT_MYSQL_USERNAME:root}
          password: ${IOT_MYSQL_PASSWORD:mI8%pB1*gD}
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: ${IOT_TDENGINE_URL:jdbc:TAOS-RS://8.130.107.120:6041/iot}
          username: ${IOT_TDENGINE_USERNAME:root}
          password: ${IOT_TDENGINE_PASSWORD:Fc11QetNg4RX}
          driver-class-name: com.taosdata.jdbc.rs.RestfulDriver

  data:
    redis:
      host: ${IOT_REDIS_HOST:8.130.107.120}
      port: ${IOT_REDIS_PORT:6379}
      password: ${IOT_REDIS_PASSWORD:1QAZ2wsx___}
      database: ${IOT_REDIS_DATABASE:8}
      timeout: 10s

logging:
  level:
    root: info
    com.ghlzm.iot: debug

iot:
  mqtt:
    broker-url: ${IOT_MQTT_BROKER_URL:tcp://8.130.107.120:1883}
    username: ${IOT_MQTT_USERNAME:emqx}
    password: ${IOT_MQTT_PASSWORD:1qaz2wsx}

  telemetry:
    storage-type: mysql

  rule:
    enabled: false

  ota:
    enabled: false
